language: node_js
node_js: [14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4]
services:
  - "mongodb"
script: "npm run-script test-travis"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"